apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: messaging
  name: messaging
spec:
  containers:
  - image: rabbitmq:3.9-alpine
    name: messaging
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
